[package]
name = "person-service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
# axum = "0.8.4"
hyper = { version = "0.14", features = ["full"] }
httprouter = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"